const theme = {
  light: {
    primary: '#504DB6',
    primaryTwo: '#504DB6',
    primaryThree: '#504DB6',
    primaryFour: '#504DB6',
    secondary: '#8775FE',
    background: '#fff',
    backgroundTwo: '#F8F8F8',
    backgroundThree: '#F8F8F8',
    backgroundFour: '#fff',
    divider: '#EBEBED',
    text: '#000',
    textTwo: '#000',
    textThree: '#6F6F6F',
    textFour: '#85868A',
    textFive: '#404040',
    shadow: 'rgba(194, 193, 248, 0.3)',
  },
  dark: {
    primary: '#504DB6',
    primaryTwo: '#B2A7FF',
    primaryThree: '#BEB5FF',
    primaryFour: '#CAC2FF',
    secondary: '#8775FE',
    background: '#000',
    backgroundTwo: '#1B1B1B',
    backgroundThree: '#F8F8F8',
    backgroundFour: '#1B1B1B',
    divider: '#7A7A7A',
    text: '#fff',
    textTwo: '#EEEEEE',
    textThree: '#EEEEEE',
    textFour: '#EEEEEE',
    textFive: '#fff',
    shadow: 'transparent',
  },
}

export default theme